import daisyui from 'daisyui';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        manrope: ['Manrope', 'sans-serif'],
      },
      colors: {
        "on-secondary": "#ffffff",
        "secondary-container": "#c0edd4",
        "on-primary-fixed": "#002114",
        "secondary-fixed": "#c0edd4",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-fixed": "#271900",
        "on-secondary-fixed-variant": "#264e3c",
        "tertiary-fixed-dim": "#ffba29",
        "tertiary-fixed": "#ffdea9",
        "outline": "#717973",
        "on-error-container": "#93000a",
        "surface-tint": "#3f6653",
        "on-background": "#191c1d",
        "on-surface-variant": "#414844",
        "on-error": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "primary-fixed-dim": "#a5d0b9",
        "primary": "#012d1d",
        "inverse-surface": "#2e3132",
        "secondary": "#3e6653",
        "on-primary-fixed-variant": "#274e3d",
        "on-primary-container": "#86af99",
        "outline-variant": "#c1c8c2",
        "tertiary": "#352300",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#446d59",
        "surface-variant": "#e1e3e4",
        "surface-bright": "#f8f9fa",
        "on-surface": "#191c1d",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "surface-dim": "#d9dadb",
        "tertiary-container": "#513700",
        "on-tertiary-container": "#d99b00",
        "on-secondary-fixed": "#002114",
        "inverse-on-surface": "#f0f1f2",
        "background": "#f8f9fa",
        "inverse-primary": "#a5d0b9",
        "surface": "#f8f9fa",
        "on-tertiary-fixed-variant": "#5f4100",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#c1ecd4",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#a5d0b8",
        "primary-container": "#1b4332",
        "surface-container": "#edeeef",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        agrosmart: {
          "primary": "#012d1d",
          "primary-content": "#ffffff",
          "secondary": "#3e6653",
          "secondary-content": "#ffffff",
          "accent": "#ffba29",
          "accent-content": "#271900",
          "neutral": "#2e3132",
          "neutral-content": "#f0f1f2",
          "base-100": "#f8f9fa",
          "base-200": "#edeeef",
          "base-300": "#e1e3e4",
          "base-content": "#191c1d",
          "info": "#a5d0b9",
          "info-content": "#002114",
          "success": "#3f6653",
          "success-content": "#ffffff",
          "warning": "#ffdea9",
          "warning-content": "#271900",
          "error": "#ba1a1a",
          "error-content": "#ffffff",
        },
      },
    ],
  },
};
